liscense
camunda/camunda-docs-static pull request #115
Opened 2020-10-06 05:32 UTC by manishgautam30

2020-10-06 05:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-docs-static?pullRequest=115) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-docs-static?pullRequest=115) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-docs-static?pullRequest=115) it.</sub>

2020-10-09 10:31 UTC, tmetzke commented
Hey @manishgautam30,

thanks for making us aware of that!

We will have a closer look as soon as we can and provide you with proper feedback.

Best and thanks,
Tobias

2020-10-09 12:21 UTC, ThorbenLindhauer requested changes
Hi @manishgautam30,

Thanks for your PR and spotting that the repository has no license. Instead of MIT, we would like to apply CC BY SA 3.0. This is the license that we use for our other docs repository, https://github.com/camunda/camunda-docs-manual. Can you please update your pull request accordingly?

Best regards,
Thorben

2020-10-16 07:28 UTC, ThorbenLindhauer commented
Closing this PR due to inactivity. Please let us know/reopen the PR if you want to continue.

2020-10-16 07:28 UTC, closed without merging