chore(get-started): update RPA guide with AAI
camunda/camunda-docs-static pull request #173
Opened 2021-05-06 13:59 UTC by tmetzke

related to CAM-13252

2021-05-07 12:55 UTC, mboskamp requested changes
Nice work! This reads very well.

I think content-wise we are good to go. One thing that we could think about is adding a link to the next topic at the end of every page. Since the pages built upon each other, it would make it easier to read through them in order.

I ran the text through Grammarly and included suggestions for typos and formulation improvements. Feel free to ignore them wherever you disagree. Most of them are related to punctuation anyways :D

Some general hints:

* In some lists, we start a bullet point with a capital letter and in some, we start small. In general, we should try to stick with one format I think. I would vote for capitalization of the first letter, as it is mandatory for complete sentences and [suggested](http://www.imperial.ac.uk/brand-style-guide/writing/grammar/punctuation/bullet-points/) even for lists of short items.
* I changed "in order to" to simply "to" on several occasions. I think it sounds and reads easier but feel free to disagree.

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +The data that these scripts need as input should be configured as IN arguments in UiPath Studio. The RPA Bridge will then pass the Camunda task input parameters via the UiPath Orchestrator into the U
```suggestion
The data that these scripts need as input should be configured as IN arguments in UiPath Studio. The RPA Bridge will then pass the Camunda task input parameters via the UiPath Orchestrator into the UiPath Robot. In a similar way, the OUT arguments of UiPath will be returned back into the Camunda engine as task output parameters. The names of these IN and OUT arguments will be used in the Cawemo Catalog.
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +In case you have trouble setting up and running your Automation Anywhere scripts via the Automation Anywhere Control Room please refer to the [Automation Anywhere documentation](https://docs.automati
```suggestion
In case you have trouble setting up and running your Automation Anywhere scripts via the Automation Anywhere Control Room, please refer to the [Automation Anywhere documentation](https://docs.automationanywhere.com/).
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +In order to create a new template, you need to
```suggestion
To create a new template, you need to:
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +* Inside this Catalog Project create a new "Service Task Template"
According to http://www.imperial.ac.uk/brand-style-guide/writing/grammar/punctuation/bullet-points/, the items in this list should not be capitalized because they complete the sentence that introduces the list.

```suggestion
* open the Catalog project and create a new “Service Task Template” 
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +  * Template name: Define a human readable name, such that users will understand which RPA bot this template refers to
```suggestion
  * Template name: Define a human-readable name, such that users will understand which RPA bot this template refers to
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +  * Service task label: leave empty if you do not want to give a defaul label to the BPMN service task
```suggestion
  * Service task label: leave empty if you do not want to give a default label to the BPMN service task
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +  * for each RPA bot input argument add one entry with the matching name
```suggestion
  * for each RPA bot input argument, add one entry with the matching name
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +  * for each RPA bot output argument add one entry with the matching name
```suggestion
  * for each RPA bot output argument, add one entry with the matching name
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +Before a template can be used in the Camunda Modeler it needs to be published once by clicking the “Publish” button in the upper right corner. If you like you can provide a name for the published ver
```suggestion
Before a template can be used in the Camunda Modeler, it needs to be published once by clicking the “Publish” button in the upper right corner. If you like, you can provide a name for the published version. If you need to adjust your template later on, you can publish a new version of it.
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +If you want to create templates for other elements you can learn more about [advanced configuration options of templates](https://docs.camunda.org/manual/latest/modeler/element-templates/).
```suggestion
If you want to create templates for other elements, you can learn more about [advanced configuration options](https://docs.camunda.org/manual/latest/modeler/element-templates/).
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +In order to trigger the RPA Bot from Camunda, create a new BPMN process as follows:
```suggestion
To trigger the RPA Bot from Camunda, create a new BPMN process as follows:
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +* Click on "Catalog" in the Property Panel and you will see an overlay with a list of your templates
```suggestion
* Click on "Catalog" in the Property Panel, and you will see an overlay with a list of your templates
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +* Complete your BPMN process diagram with further elements as you see fit (e.g. User Tasks)
```suggestion
* Complete your BPMN process diagram with further elements as you see fit (e.g., User Tasks)
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +* In the success notification click on "Open in Camunda Cockpit". You will see the running process instance with its current state
```suggestion
* In the success notification, click on "Open in Camunda Cockpit". You will see the running process instance with its current state.
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +* Click the Run icon in the toolbar ("Start Current Diagram") and confirm the dialogs. This will deploy the process diagram and trigger a new process instance
```suggestion
* Click the Run icon in the toolbar ("Start Current Diagram") and confirm the dialogs. This will deploy the process diagram and trigger a new process instance.
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/orchestrating-bots.md
> +When the Bot is completed, you can switch back to the Camunda Cockpit and observe the progress of your process instance. Remember that you might need to switch to the History View in case your proces
```suggestion
When the bot is completed, you can switch back to the Camunda Cockpit and observe the progress of your process instance. Remember that you might need to switch to the History View in case your process ends after the RPA task.
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/error-handling.md
> +Now that we can [Orchestrate RPA Bots](../orchestrating-bots), let's have a look at how to react to a failing RPA bot or - generally speaking - how to handle the result of a bot as a BPMN error. Plea
```suggestion
Now that we can [Orchestrate RPA Bots](../orchestrating-bots) let's have a look at how to react to a failing RPA bot or - generally speaking - how to handle the result of a bot as a BPMN error. Please note that the features presented here only work with a Camunda Platform 7.15 or later.
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/error-handling.md
> +* Technical Error: An RPA bot fails with a specific error message and stacktrace, indicating a technical error that should be treated as an exceptional business case that can be handled in a structur
```suggestion
* Technical Error: An RPA bot fails with a specific error message and stack trace, indicating a technical error that should be treated as an exceptional business case that can be handled in a structured way in the process model.
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/error-handling.md
> +In order to throw BPMN errors from your service tasks, add an error definition to your template in the Catalog in Cawemo.
```suggestion
To throw BPMN errors from your service tasks, add an error definition to your template in the Catalog in Cawemo.
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/error-handling.md
> +* Name: human readable name for your error
```suggestion
* Name: human-readable name for your error
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/error-handling.md
> +  * You can refer to the Output Parameters as they are named in the Output Parameter section
```suggestion
  * You can refer to the Output Parameters as they are named in the Output Parameter section.
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/error-handling.md
> +  * Don't rely on Output Parameters to be available in such cases, as those might not be returned on failure by the bot
```suggestion
  * Don't rely on Output Parameters to be available in such cases, as those might not be returned on failure by the bot.
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/error-handling.md
> +The first Throw Expression that matches will be applied, any following expressions will not be evaluated.
```suggestion
The first Throw Expression that matches will be applied. Any following expressions will not be evaluated.
```

2021-05-07 12:55 UTC, mboskamp commented on get-started/content/rpa/error-handling.md
> +In order to handle the BPMN error that we just defined, we need to create a Boundary Error Event at the service task. This boundary event can now reference the error definition we created with the te
```suggestion
To handle the BPMN error that we just defined, we need to create a Boundary Error Event at the service task. This boundary event can now reference the error definition we created with the template to properly catch it.
```

2021-05-10 16:06 UTC, volkergersabeck requested changes

2021-05-10 16:06 UTC, volkergersabeck commented on get-started/content/rpa/error-handling.md
> +# Scenarios
I could imagine that we start this page with the Scenarios chapter to motivate why you would want to work with BPMN Errors. After that, people can read about configuration, throwing and catching.

2021-05-11 06:14 UTC, tmetzke commented on get-started/content/rpa/installation.md
> +* Remember the password of that user or alternatively [create an API key](https://docs.automationanywhere.com/bundle/enterprise-v2019/page/enterprise-cloud/topics/control-room/control-room-api/cloud-
Totally agree, I had my issues with that part of the text really 🙂

2021-05-11 06:24 UTC, tmetzke commented on get-started/content/rpa/installation.md
> +Unless you already have a running Camunda Platform 7.14 or later installation, please
I wasn't all that sure about it. Are we documenting the minimal version requirements here or always updating that in the future to the latest ones? Updating the link to the latest downloads is obvious, but textually we might also keep the minimal versions. If someone with 7.14 installed comes along and reads this, that person might think "Oh, well, I have to upgrade first, will I do that?". I think it could make the guide more relevant to more people if we keep minimal version requirements. Let me know what you think. 🙂

2021-05-11 06:28 UTC, tmetzke commented on get-started/content/rpa/error-handling.md
> +# Scenarios
That is a very good idea, I like that 👍

2021-05-17 21:22 UTC, akeller reviewed
I reviewed for grammar, consistency, and sentence flow. This looks really good overall!

Another comment I wanted to make that's not unique to this PR was I see inconsistencies with capitalization of BPMN symbols. Service Task is sometimes service task, same with call activity and Call Activity, although its usually capitalized. I would like to get these standardized. While the OMG spec shows them capitalized, most documentation in the industry uses lower case when referring to BPMN symbols. All of this to say, I did not suggest changes for those items because I didn't want to be inconsistent within this guide vs. the rest of the Camunda Platform docs.

2021-05-17 21:22 UTC, akeller commented on get-started/content/rpa/installation.md
> +  * `webhook`: add `#` to the beginning of each line under `webhook`, so it is not considered by the Bridge
```suggestion
* Add `#` to the beginning of each line under `automation-anywhere-api`, so it is not considered by the Bridge
* Under the `uipath-api` element, adjust the following
  * `url`: set to `https://platform.uipath.com/`
  * `account-name`: the Account Logical Name from the API Access overlay
  * `tenant-name`: the Tenant Logical Name from the API Access overlay
  * `folder-path`: adjust to the name of the folder you want to work with, in case you do **NOT** want to work with a folder called "Default"
  * `organization-unit-id`: see above how to [retrieve your organization unit id](#uipath)
  * Under the `authentication` element, adjust the following
    * `type`: 
    * `auth-url`: switch to `https://account.uipath.com/oauth/token`
    * `user`: the Client Id from the API Access overlay
    * `key`: the User Key from the API Access overlay
  * `status-update-method`: set to `polling`
  * `webhook`: add `#` to the beginning of each line under `webhook`, so it is not considered by the Bridge
```

This is small, but all other lists are capitalized, often with punctuation. Was this intentional to not do it here?

2021-05-17 21:22 UTC, akeller commented on get-started/content/rpa/installation.md
> +  * if you want to use an [API key](https://docs.automationanywhere.com/bundle/enterprise-v2019/page/enterprise-cloud/topics/control-room/control-room-api/cloud-authenticate-apikey.html) instead, put
```suggestion
* Add `#` to the beginning of each line under `uipath-api`, so it is not considered by the Bridge
* Under the `automation-anywhere-api` element, adjust the following:
  * `url`: set to the base URL of your Automation Anywhere Controlroom instance
  * `user`: the name of the user with bot runner permissions, this user is starting the bots in your Automation Anywhere instance
  * `password`: the user's password
  * If you want to use an [API key](https://docs.automationanywhere.com/bundle/enterprise-v2019/page/enterprise-cloud/topics/control-room/control-room-api/cloud-authenticate-apikey.html) instead, put a `#` in front of `password`, remove the one in front of `api-key` and add your API key to that property
```
Again, small but correcting for inconsistencies.

2021-05-17 21:22 UTC, akeller commented on get-started/content/rpa/installation.md
> +When being logged in to Cawemo:
Unsure about this fragment. Do you mean "After logging into Cawemo:" or "While logged into Cawemo"?

2021-05-17 21:22 UTC, akeller commented on get-started/content/rpa/orchestrating-bots.md
> +If the new bot uses input and/or output variables, make sure to configure those variables correctly as input or output variables in the bot editor in Automation Anywhere Control Room. To provide inpu
```suggestion
If the new bot uses input and/or output variables, make sure to configure those variables correctly as input or output variables in the bot editor in Automation Anywhere Control Room. To provide input variables to the bot, configure input mapping for each variable that should be passed to the bot on the task through either Cawemo or the Camunda Modeler. To send output variables from the bot to Camunda, configure input mapping on the task through either Cawemo or the Camunda Modeler and make sure to mark the variables as output in the Automation Anywhere Control Room.
```

2021-05-17 21:22 UTC, akeller commented on get-started/content/rpa/orchestrating-bots.md
> +Once the RPA bot works as expected and was released, make sure that the bot and all necessary resources are available publicly.
```suggestion
Once the RPA bot works as expected and is released, make sure that the bot and all necessary resources are available publicly.
```

The tense of this sentence felt a bit off.

2021-05-17 21:22 UTC, akeller commented on get-started/content/rpa/orchestrating-bots.md
> +* create a new "Service Task Template" inside this new catalog project
```suggestion
* Open the "Home" view of Cawemo
* Create a new "Catalog Project" using the split button and give it a name
* Create a new "Service Task Template" inside this new catalog project
```

2021-05-17 21:22 UTC, akeller commented on get-started/content/rpa/orchestrating-bots.md
> +After starting a new process instance and reaching the RPA Service Task, you can see new entries in the historical activity lists in Automation Anywhere Control Room representing the started RPA bot.
```suggestion
After starting a new process instance and reaching the RPA Service Task, you can see new entries in the historical activity lists in the Automation Anywhere Control Room representing the started RPA bot.
```

2021-05-17 21:22 UTC, akeller commented on get-started/content/rpa/orchestrating-bots.md
> +When the bot is completed, you can switch back to the Camunda Cockpit and observe the progress of your process instance. Remember that you might need to switch to the History View in case your proces
```suggestion
When the bot has completed, you can switch back to the Camunda Cockpit and observe the progress of your process instance. Remember that you might need to switch to the History View in case your process ends after the RPA task.
```

2021-05-17 21:22 UTC, akeller commented on get-started/content/rpa/requirements.md
> +* how to work with process variables as part of JUEL expressions
I have two thoughts here:

Change the sentence to "In order to succeed with this getting started guide, we expect that you already know how to" and start each item in the list with their verb capitalized.

-OR-

Capitalize all the H's in the list.

2021-05-18 06:35 UTC, tmetzke commented on get-started/content/rpa/installation.md
> +  * `webhook`: add `#` to the beginning of each line under `webhook`, so it is not considered by the Bridge
Simply missed that one 😃

2021-05-18 06:35 UTC, tmetzke commented on get-started/content/rpa/installation.md
> +When being logged in to Cawemo:
```suggestion
After logging into Cawemo:
```

2021-05-18 06:36 UTC, tmetzke commented on get-started/content/rpa/requirements.md
> +* how to work with process variables as part of JUEL expressions
```suggestion
* How to create and trigger robots with your RPA vendor (UiPath or AutomationAnywhere)
* How to model and execute BPMN process diagrams with the Camunda stack
* How to work with process variables as part of JUEL expressions
```

2021-05-18 06:39 UTC, tmetzke commented on get-started/content/rpa/installation.md
> +Unless you already have a running Camunda Platform 7.14 or later installation, please
Regarding style, I would stick with "or later" as we are using throughout this guide 😃

2021-05-18 06:54 UTC, mboskamp approved these changes

2021-05-26 06:21 UTC, merged

2021-05-26 06:22 UTC, tmetzke commented
@volkergersabeck, I merged it for now. 
Happy to discuss follow-ups regarding the points you mentioned if you like.