Update service-task.md
camunda/camunda-docs-static pull request #226
Opened 2021-12-22 10:33 UTC by FabioBentoLuiz

The casting with Long will fail on the step (link below) where the generic form screenshot sugests seting "amount" as Integer.
https://docs.camunda.org/get-started/quick-start/user-task/#work-on-the-task

2021-12-22 10:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-docs-static?pullRequest=226) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-docs-static?pullRequest=226) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-docs-static?pullRequest=226) it.</sub>

2022-01-03 13:52 UTC, mboskamp requested changes
Hi @FabioBentoLuiz,

Thanks for the PR. You are right, it should be `Integer`. The corresponding [example repository](https://github.com/camunda/camunda-get-started-quickstart/blob/1f4f17c84d3a286aa9a648124bc7fbbae08f0f7f/java/charge-card-worker/src/main/java/org/camunda/bpm/getstarted/chargecard/ChargeCardWorker.java#L42) also uses `Integer` over `Long`.

I don't think the casts are even necessary. Let's remove them. This is then also consistent with the example. What do you think?

2022-01-03 13:52 UTC, mboskamp commented on get-started/content/quick-start/service-task.md
>            String item = (String) externalTask.getVariable("item");
```suggestion
          String item = externalTask.getVariable("item");
```

2022-01-03 13:52 UTC, mboskamp commented on get-started/content/quick-start/service-task.md
> +          Integer amount = (Integer) externalTask.getVariable("amount");
```suggestion
          Integer amount = externalTask.getVariable("amount");
```

2022-01-03 22:02 UTC, FabioBentoLuiz commented on get-started/content/quick-start/service-task.md
> +          Integer amount = (Integer) externalTask.getVariable("amount");
Hi @mboskamp,
Some steps later on the Get Started section (https://docs.camunda.org/get-started/quick-start/decision-automation/#inspect-using-cockpit-and-tasklist), there are two screenshots setting the amount as Long to start new process instances.

It is better updating them to use Integer as well, right?

2022-01-04 09:30 UTC, mboskamp commented on get-started/content/quick-start/service-task.md
> +          Integer amount = (Integer) externalTask.getVariable("amount");
Oh, nice catch. We can take care of updating the screenshots with the next release. For now, let's merge the code snippet changes first.

2022-01-04 09:31 UTC, merged