chore(quickstart): add jaxb-impl dependency and help with using Tasklist and Modeler UI
camunda/camunda-docs-static pull request #256
Opened 2022-03-24 02:04 UTC by alexcorremans

- require dependency jaxb-impl for Java 9 and above
- use the create space tool before adding the user task
- add a task filter in Tasklist
- explain how to configure input column in DMN table

related to CAM-14436

2022-03-24 02:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-docs-static?pullRequest=256) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-docs-static?pullRequest=256) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-docs-static?pullRequest=256) it.</sub>

2022-04-04 07:03 UTC, marstamm reviewed
Looks okay. Added a few styling suggestions

2022-04-04 07:03 UTC, marstamm commented on get-started/content/quick-start/install.md
> +`/camunda-bpm-run-7.x.x/configuration/userlib` {{< /note >}}
```suggestion
`/camunda-bpm-run-7.x.x/configuration/userlib`
{{< /note >}}
```

2022-04-04 15:49 UTC, ThorbenLindhauer requested changes
Thanks for your improvements. I'm questioning if the jaxb dependency is needed, please see my detailed comment.

2022-04-05 01:13 UTC, alexcorremans commented on get-started/content/quick-start/install.md
> +{{< /note >}}
You got me! I was indeed running Java 17. I've now tested both with Java 15 and 7.16.0, and Java 17 with 7.17.0-alpha6, and can confirm both are working. 

I agree the guide should be more explicit on using a supported Java version. I'll work on that now.

2022-04-05 11:21 UTC, ThorbenLindhauer approved these changes

2022-04-05 11:21 UTC, ThorbenLindhauer commented
Thanks for the contribution, I merged it via https://github.com/camunda/camunda-docs-static/commit/8a17972ee62ca080cedf747963c607126e1d6581 to master. We will release the changes with the 7.17 release next week.

2022-04-05 11:21 UTC, closed without merging