Change to the new artifactory domain
camunda/camunda-docs-static pull request #257
Opened 2022-03-29 08:51 UTC by chaima-mnsr

Related to INFRA-3183

2022-03-29 09:06 UTC, Langleu commented on build.gradle
> +  nexusUrl = System.getProperty('nexus.url', 'https://artifacts.camunda.com')
`/nexus` was a redirect to `/artifactory`
--> `https://artifacts.camunda.com/artifactory`

2022-03-29 14:36 UTC, ThorbenLindhauer requested changes
There seems to be a problem with browsing via the `artifacts` domain which I think we should resolve before we merge and publish the changed URLs.

2022-03-29 14:36 UTC, ThorbenLindhauer commented on get-started/content/apache-maven.md
> +https://artifacts.camunda.com/ui/native/camunda-bpm-ee
This URL doesn't work for me: It requires me to log in, but then just redirects to https://camunda.jfrog.io/ui/packages. If I access the URL again, it prompts for login again. In the artifacts explorer, I do have access to camunda-bpm-ee. 

On a related note, when I am logged in and access https://artifacts.camunda.com/ui/native/private/org/camunda/bpm/camunda-engine/, I only see the publicly available (i.e. non-ee) artifacts. If I use https://camunda.jfrog.io/ui/native/private/org/camunda/bpm/camunda-engine/ instead, I can see all artifacts.

2022-03-29 14:36 UTC, ThorbenLindhauer commented on get-started/content/apache-maven.md
> + https://artifacts.camunda.com/artifactory/camunda-bpm-ee/
For the same reason as above, this link does currently not work as intended for me.

2022-03-30 06:55 UTC, chaima-mnsr commented on get-started/content/apache-maven.md
> +https://artifacts.camunda.com/ui/native/camunda-bpm-ee
This is a known issue that we will fix once the new URL is announced to the customers. However, we don't expect the customers to be affected by that since this happens only if you login using SSO and the customers use LDAP.

2022-03-30 06:58 UTC, chaima-mnsr commented on get-started/content/apache-maven.md
> + https://artifacts.camunda.com/artifactory/camunda-bpm-ee/
This is a known issue that we will fix once the new URL is announced to the customers. However, we don't expect the customers to be affected by that since this happens only if you login using SSO and the customers use LDAP. 

This problem also does not affect the CI.

2022-03-30 07:37 UTC, ThorbenLindhauer approved these changes
Thanks for explaining, I will go ahead merging the changes then.

2022-03-30 07:42 UTC, merged