chore(openapi): test redirect
camunda/camunda-docs-static pull request #304
Opened 2022-10-21 12:14 UTC by mboskamp

2022-11-04 09:10 UTC, tasso94 approved these changes
Looks good to me 👍

2022-11-11 12:11 UTC, mboskamp commented on config/live/.htaccess
> +RewriteRule ^manual/(latest|develop)/reference/rest/$ /rest/camunda-bpm-platform/7.19-SNAPSHOT/ [R=301,L,NE]
```suggestion
RewriteRule ^manual/(latest|develop)/reference/rest/specification/$ /rest/camunda-bpm-platform/7.19-SNAPSHOT/ [R=301,L,NE]
```

2022-11-11 12:11 UTC, mboskamp commented on config/stage/.htaccess
> +RewriteRule ^manual/(latest|develop)/reference/rest/$ /rest/camunda-bpm-platform/7.19-SNAPSHOT/ [R=301,L,NE]
```suggestion
RewriteRule ^manual/(latest|develop)/reference/rest/specification/$ /rest/camunda-bpm-platform/7.19-SNAPSHOT/ [R=301,L,NE]
```

2022-11-15 16:32 UTC, tasso94 requested changes
Great job! Looks good to me in general. Just two hints added below ⬇️

2022-11-16 09:28 UTC, mboskamp commented on config/stage/.htaccess
> +RewriteRule ^manual/(latest|develop)/reference/rest/specification/$ /rest/camunda-bpm-platform/7.19-SNAPSHOT/ [R=301,L,NE]
```suggestion
RewriteRule ^manual/(latest|develop)/reference/rest/specification/(.*)$ /rest/camunda-bpm-platform/7.19-SNAPSHOT/$2 [R=301,L,NE]
RewriteRule ^manual/([^/]+)/reference/rest/specification/(.*)$ /rest/camunda-bpm-platform/$1/$2 [R=301,L,NE]
```

2022-11-23 15:26 UTC, tasso94 approved these changes

2022-12-13 12:29 UTC, merged