Update announcement.md
camunda/camunda-docs-static pull request #351
Opened 2023-04-03 14:44 UTC by toco-cam

https://github.com/camunda/camunda-bpm-platform/issues/3243

2023-04-04 10:47 UTC, yanavasileva reviewed
This is an exiting announcement. 👍 
Please have a look at the suggestions below.

2023-04-04 10:47 UTC, yanavasileva commented on enterprise/content/announcement.md
> +* End of Support for JBoss Redhat EAP 7.2 / 7.3
Suggestion about the naming:
```suggestion
* End of Support for JBoss EAP 7.2 / 7.3
```

2023-04-04 10:47 UTC, yanavasileva commented on enterprise/content/announcement.md
> +* End of Support for Oracke 12c
Typo:
```suggestion
* End of Support for Oracle 12c
```

2023-04-04 10:47 UTC, yanavasileva commented on enterprise/content/announcement.md
> +* End of Support for Wildfly 14 / 15 / 16 / 17 / 18 / 19 / 20 / 21 / 22 / 24 / 25
We already dropped support for WildFly 14 in 7.19:
```suggestion
* End of Support for WildFly 15 / 16 / 17 / 18 / 19 / 20 / 21 / 22 / 24 / 25
```

2023-04-04 10:47 UTC, yanavasileva commented on enterprise/content/announcement.md
> +__Release Date:__ scheduled for 11th of October 2023
If I am not mistaken, second Tuesday in October is 10th.
```suggestion
__Release Date:__ scheduled for 10th of October 2023
```

2023-04-04 10:47 UTC, yanavasileva commented on enterprise/content/announcement.md
> +* End of Support for Velocity. XQuey Script Engines
Typo:
```suggestion
* End of Support for Velocity. XQuery Script Engines
```

2023-04-05 10:00 UTC, ThorbenLindhauer requested changes
I agree with Yana's comments and have added two more. I also double-checked against our planning sheet, this looks good to me.

2023-04-11 10:58 UTC, yanavasileva commented
@toco-cam, thank you for applying the review hints. Could you please have a look again at the comments for the JBoss EAP and Oracle names?

2023-04-11 11:56 UTC, merged