[Acquisition team] Add buttons to navbar
camunda/camunda-docs-static pull request #384
Opened 2023-08-08 16:04 UTC by akeller

Follow up to https://github.com/camunda/camunda-docs-theme/pull/41 and adding the changes to this part of the docs site.

There were many other changes I noticed locally, including changes to shortcode files and sitemaps, but these are not in the scope of this PR.

2023-08-08 18:48 UTC, pepopowitz requested changes
All of my feedback applies to all 3 "sites", not just the one I commented on.

2023-08-08 18:48 UTC, pepopowitz commented on enterprise/themes/camunda/layouts/partials/header.html
> +  <link rel="canonical" href="{{ $.Site.Params.canonicalBasePath }}{{ $permalink }}" />
These older changes are dragged along from previous work re: C7 SEO. They're adding a `link rel="canonical"`, with the version scrubbed from the path, using a `canonicalBasePath` from the configuration. This site doesn't use versions, so the version-scrubbing logic should have no effect....however the `canonicalBasePath` setting is not included in these changes, which would result in relative canonical URLs.

This _might_ be fine, because Google does not _forbid_ relative canonical URLs. [But they do recommend using absolute](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls?visit_id=638271166349961615-3759461083&hl=en&rd=2#rel-canonical-link-method), to deal with staging sites. 

We should probably do 1 of 2 things: 

1. Exclude these changes from this PR, which is IMO annoying but I've been advised to pick and choose these kinds of changes in the past so there is precedent....or
2. Add a proper `canonicalBasePath` configuration setting to this PR.

*Note:* this feedback applies to each of the enterprise, get-started, and security sub-sites.

2023-08-08 18:48 UTC, pepopowitz commented on enterprise/themes/camunda/layouts/partials/header.html
> +<nav class="site-menu">
FYI: This is also dragged along from previous C7 work, but it should have no negative effect. I had avoided bringing it over here in the past, under advisement to deploy changes where I didn't _need_ them.

2023-08-08 18:48 UTC, pepopowitz commented on get-started/themes/camunda/assets/css/docs.css
As in [the other similar PR for camunda-docs-manual](https://github.com/camunda/camunda-docs-manual/pull/1515), I think this large diff is a case of not running the `optimize` command [described in the theme docs](https://github.com/camunda/camunda-docs-theme#consuming-the-theme)?

> 2) Build and update the theme in the target location by either running:
>    1) `grunt build` for building and syncing non-minified assets
>    2) Run additionally `grunt optimize` for building and syncing minified assets 

For browser performance reasons, we should minimize these assets.

2023-08-08 18:53 UTC, akeller commented on get-started/themes/camunda/assets/css/docs.css
Done

2023-08-08 18:56 UTC, akeller commented on enterprise/themes/camunda/layouts/partials/header.html
> +  <link rel="canonical" href="{{ $.Site.Params.canonicalBasePath }}{{ $permalink }}" />
I'll remove this from all sites in case we need to back out these changes in the future. Canonical work should be done in a separate PR.

2023-08-08 18:56 UTC, akeller commented on enterprise/themes/camunda/layouts/partials/header.html
> +<nav class="site-menu">
I will remove this.

2023-08-08 19:04 UTC, akeller commented
Hmm... this has a lot more deletions than I expected to see.

2023-08-08 19:18 UTC, pepopowitz commented
> Hmm... this has a lot more deletions than I expected to see.

I think it's because 2 of the 3 sites didn't have minified assets.

So, nice work! 

<img src="https://media1.giphy.com/media/D7z8JfNANqahW/giphy.gif"/>

2023-08-08 19:19 UTC, pepopowitz approved these changes

2023-08-15 15:01 UTC, tasso94 approved these changes
Looks good to me. 👍

2023-08-15 16:17 UTC, merged