Update announcement.md
camunda/camunda-docs-static pull request #421
Opened 2023-12-08 07:58 UTC by toco-cam

2023-12-12 14:04 UTC, tasso94 requested changes

2023-12-12 14:04 UTC, tasso94 commented on enterprise/content/announcement.md
> +__Release Date:__ scheduled for 8th of April 2024
❌ I think this is not the correct release date of 7.22. Shouldn't it be October?

2023-12-12 16:40 UTC, toco-cam commented on enterprise/content/announcement.md
> +__Release Date:__ scheduled for 8th of April 2024
You are right, this is 7.23

2023-12-13 11:01 UTC, tasso94 approved these changes
Looks good to me 👍

2023-12-13 15:18 UTC, merged